Portfolio: mobile version pull request
Ney2/Portfolio pull request #2
Opened 2022-05-28 14:00 UTC by Ney2

This is a pull request for the ' Portfolio: mobile version' project.
1. Add the work and about section in index.html file
2. Add styling for work and about section in style.css file

2022-05-28 15:00 UTC, Chimwemwe-127001 requested changes
# Required Changes ♻️ :warning: 
### Hi @saqibjavaiddev <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="19px" alt="hi">
Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif" alt="so close">

## Highlights :+1: 
- Repo looks professional :briefcase:
- README.md looks professional :briefcase:

## Required Changes ♻️
- [ ] You must stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 15:00 UTC, Chimwemwe-127001 commented on index.html
> +    <a href="#">Get My Resume</a>
- [ ] I suggest you follow the Figma as close as possible for this part of the project aswell.

Your design 
![Screenshot from 2022-05-28 16-56-21](https://user-images.githubusercontent.com/52143815/170830894-8287e841-f184-4e22-bb8b-b4eb322d416e.png)

The figma design
![Screenshot from 2022-05-28 16-59-34](https://user-images.githubusercontent.com/52143815/170830936-a7d2f031-714b-4caf-adfa-fb5727df8901.png)

2022-05-28 17:13 UTC, Ney2 commented
Updated styles.css file to meet the requirements.

2022-05-28 18:12 UTC, cwaku requested changes
Hi @Ney2 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
![](https://media.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif)
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 18:12 UTC, cwaku commented on index.html
> +   </div>
- [ ] As requested by the previous reviewer, it is required to have your project as identical to the Figma template as possible. The section should use the font and colours (background and font) defined for the template. Kindly consider adding a bit more CSS for us to achieve this and make your project rock 😃

<html>
<body>
<!--StartFragment--><p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

Figma design | Your design
-- | --
![image](https://user-images.githubusercontent.com/29071984/170837269-6c0dc6a2-1937-4ff9-aea0-75e3120232fb.png) | ![image](https://user-images.githubusercontent.com/29071984/170837322-3ac450ba-ce76-4e8e-b41b-7ec98d39c8fb.png)
 -- | ![image](https://user-images.githubusercontent.com/29071984/170837374-a3d9b65e-d558-47cb-8dd1-33008beb5c17.png)




<!--EndFragment-->
</body>
</html>

2022-05-28 18:12 UTC, cwaku commented on index.html
> +    <a href="#">Get My Resume</a>
- [ ] I would have made this optional but while you are at it fixing the other changes, kindly change the font here and also make the "Get my resume" button a little bigger as shown in the Figma template.

<html>
<body>
<!--StartFragment--><p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

Your design | Figma design
-- | --
![image](https://user-images.githubusercontent.com/29071984/170837761-fd147a04-fed9-4dca-aa41-a2c9eb5e16f1.png)  |  ![image](https://user-images.githubusercontent.com/29071984/170837734-625adadc-c290-4c19-844d-f221f950fec6.png)


<!--EndFragment-->
</body>
</html>

2022-05-28 18:38 UTC, Ney2 commented
Update styles. css file

2022-05-28 19:37 UTC, jaflih requested changes
Hi @Ney2  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


 ## Highlights

Repo looks professional 💼
README.md looks professional 💼

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +}
Here the problem is you did't take the good font, you selected the Crete Round italic font, that's why your text is in italic. 
Please go to google font and select the good font
`
@import url("https://fonts.googleapis.com/css2?family=Crete+Round:ital@1&display=swap");
`

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +  width: 50%;
As asked by the previous reviewer, you have to change the size of your image.
Here you give a value of 50% that's why it doesn't stick to Figma,
Please change 50% by 100% to have it like in the Template 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/7243132/170840310-28f43d96-cc8a-4f80-8cf5-19ee6c5bd932.png">

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +.work-content a {
Please remove the border to stick to Figma

<img width="654" alt="image" src="https://user-images.githubusercontent.com/7243132/170840357-7106bccd-ee12-425e-a2a3-b1d8c80c9a03.png">

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +  border: 1px solid black;
Please remove the border to stick to hte Template
<img width="654" alt="image" src="https://user-images.githubusercontent.com/7243132/170840386-286df49f-38bd-4971-8215-9afa3fbfb8e1.png">

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +  font-family: 'Crete Round', Arial, sans-serif;
As required by the previous reviewer, please use the good font

2022-05-28 19:37 UTC, jaflih commented on css/styles.css
> +  font-family: 'Crete Round', Arial, sans-serif;
As required by the previous reviewer, please use the good font

2022-05-30 13:46 UTC, Ney2 commented
Update styles.css file to meet Figma requirement.

2022-05-30 14:04 UTC, GzimAsani requested changes
### Hi @Ney2  
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job so far :clap: 
 
 ## Required Changes 
- [ ] Number of cards on board should be equal to 15, currently, you have 13. Kindly add those missing
- [ ] Group tasks should be assigned to both of you


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 17:18 UTC, Ney2 commented on index.html
> + <section class="works">
Thank you for your feedback but, I'm not getting what you mean

2022-05-30 17:28 UTC, Ney2 commented
Can you please tell me what cards I'm missing and also which group task should be assigned ?

2022-05-30 17:36 UTC, Ney2 commented
-  Number of cards on board should be equal to 15, currently, you have
   13. Kindly add those missing
   -  Group tasks should be assigned to both of you
   - Can you be specific, please?  What are the missing cards? And also
   which group task are you referring to? This is an individual assignment.


On Mon, May 30, 2022 at 5:04 PM Gzim Asani ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hi @Ney2 <https://github.com/Ney2>
>
> Good job so far! There are some issues that you still need to work on to
> go to the next project but you are almost there!
> Highlights
>
>    - Good job so far 👏
>
> Required Changes
>
>    - Number of cards on board should be equal to 15, currently, you have
>    13. Kindly add those missing
>    - Group tasks should be assigned to both of you
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding! clapclapclap
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear. Please, remember to tag me in your question so I can
> receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r884856064>:
>
> > +    <section class="work-section">
>
> +      <div class="title">
>
> +        <h3>My Recent Works</h3>
>
> +      </div>
>
> +    </section>
>
>
> This title should not be in the different section from the other on line
> 57, please put it there
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r884857511>:
>
> > @@ -48,5 +48,117 @@ <h2>I am a Software Developer</h2>
>
>        </div>
>
>      </section>
>
>
>
> +    <section class="work-section">
>
> +      <div class="title">
>
> +        <h3>My Recent Works</h3>
>
> +      </div>
>
> +    </section>
>
> +
>
> + <section class="works">
>
>
>
>    - It is a requirement for this to be display:grid
>
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r884860033>:
>
> > +
>
> + <section class="works">
>
> +   <div class="my-works">
>
> +     <div class="work-pic-1">
>
> +       <img src="./img/work-img/work-1.png" alt="My work" />
>
> +     </div>
>
> +     <div class="work-content">
>
> +       <h2>Multi-Post Stories</h2>
>
> +       <p>A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.</p>
>
> +       <div class="programming-languages">
>
> +         <p>css</p>
>
> +         <p>html</p>
>
> +         <p>Bootstrap</p>
>
> +         <p>Ruby</p>
>
> +       </div>
>
> +       <a href="#">See Project</a>
>
>
>
>    - [ ]This a tag, shoould follow the button styling: Active, Hover, and
>    Pressed (see design)
>
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r884860716>:
>
> > +     <div class="programming-languages">
>
> +       <p>html</p>
>
> +       <p>Bootstrap</p>
>
> +       <p>Ruby</p>
>
> +     </div>
>
>
>
>    - All of the list of project technologies should be a ul with those
>    inside as li
>
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r884864765>:
>
> > +   <div class="work-pic-2">
>
> +     <h2>Profesional Art<br> Printing Data</h2>
>
> +     <p>A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard</p>
>
> +     <div class="programming-languages">
>
> +       <p>html</p>
>
> +       <p>Bootstrap</p>
>
> +       <p>Ruby</p>
>
> +     </div>
>
> +     <a href="#">See Project</a>
>
> +   </div>
>
> +   </section>
>
> +
>
> +   <section class="About-me">
>
> +     <h2>About me</h2>
>
> +     <p>Hello I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</p>
>
> +    <a href="#">Get My Resume</a>
>
>
>
>    - This a button, should follow the button styling: Active, Hover, and
>    Pressed (see design
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ney2/Portfolio/pull/2#pullrequestreview-989388724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW3PIUSV2Z3JWDGQ4TFL2S3VMTDHLANCNFSM5XGV624A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-30 17:38 UTC, GzimAsani commented
> Can you please tell me what cards I'm missing and also which group task should be assigned ?

Please ignore that requirement, I have edited. Sorry for the confusion

2022-05-30 17:38 UTC, GzimAsani commented on index.html
> + <section class="works">
Instead of using display: flex, please use display:grid as it is a requirement

2022-05-30 17:49 UTC, Ney2 commented
Okay no problem. And thanks for your feedback.

On Mon, May 30, 2022, 8:38 PM Gzim Asani ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r885007335>:
>
> > @@ -48,5 +48,117 @@ <h2>I am a Software Developer</h2>
>        </div>
>      </section>
>
> +    <section class="work-section">
> +      <div class="title">
> +        <h3>My Recent Works</h3>
> +      </div>
> +    </section>
> +
> + <section class="works">
>
> Instead of using display: flex, please use display:grid as it is a
> requirement
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ney2/Portfolio/pull/2#discussion_r885007335>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW3PIUV3Q6FHV6FL5FI4WPLVMT4KTANCNFSM5XGV624A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-31 20:52 UTC, Ney2 commented
Update index.html file
Update styles.css file

2022-05-31 23:26 UTC, algerina approved these changes
Hi @Ney2 , 

Great work on making the changes requested by a previous reviewer :clap: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/GK7grZYLG7cs0/giphy.gif"/>

## Highlights
:heavy_check_mark: Repo looks professional 
:heavy_check_mark: README.md looks professional 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @algerina in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 04:11 UTC, merged